% =========================================================================
% Calculate the third radial component; a robust version
% -------------------------------------------------------------------------
% 输入
%	r				---	场点坐标；必须在第2维
%	l, m, n			--- 阶数；必须在第3、4、5维
%	ultra			---	超声
%	audio			---	音频声
%	a				---	活塞半径
% =========================================================================
function F3 = ...
    PAL_SHE_Radial3Robust(transducer, ultra, audio, r, l, m, n, varargin)

	%% process options
	p = inputParser;
	addParameter(p, 'Equation', 'Westervelt');
	addParameter(p, 'Region', 'outer');
	addParameter(p, 'GaussNumber', 150);
	addParameter(p, 'PrintInfo', 'Default');
    addParameter(p, 'isFocus', 0);
    addParameter(p, 'AngularAperture', 40);
	parse(p, varargin{:});
	ip = p.Results;

	% using complex method
    F3_Complex_buf1 = PAL_SHE_Radial3(...
        transducer, ultra, audio, r, l, m, n,...
        'GaussNumber', ip.GaussNumber,...
		'Region', ip.Region,...
		'Equation', ip.Equation, ...
		'Method', 'Complex', ...
        'PrintInfo', 'Mute',...
        'isFocus', ip.isFocus,...
        'AngularAperture', ip.AngularAperture);
    F3_Complex_buf2 = PAL_SHE_Radial3(...
        transducer, ultra, audio, r, l, m, n,...
        'GaussNumber', ip.GaussNumber+1,...
		'Region', ip.Region,...
		'Equation', ip.Equation, ...
		'Method', 'Complex', ...
        'PrintInfo', 'Mute',...
        'isFocus', ip.isFocus,...
        'AngularAperture', ip.AngularAperture);

	% using the Gauss number method
    F3_Gauss_buf1 = PAL_SHE_Radial3(...
        transducer, ultra, audio, r, l, m, n,...
        'GaussNumber', ip.GaussNumber,...
		'Region', ip.Region,...
		'Equation', ip.Equation, ...
		'Method', 'Gauss', ...
        'PrintInfo', 'Mute',...
        'isFocus', ip.isFocus,...
        'AngularAperture', ip.AngularAperture);
    F3_Gauss_buf2 = PAL_SHE_Radial3(...
        transducer, ultra, audio, r, l, m, n,...
        'GaussNumber', ip.GaussNumber+1,...
		'Region', ip.Region,...
		'Equation', ip.Equation, ...
		'Method', 'Gauss', ...
        'PrintInfo', 'Mute',...
        'isFocus', ip.isFocus,...
        'AngularAperture', ip.AngularAperture);

	F3 = F3_Complex_buf2;

	% p_err_Complex = abs((F3_Complex_buf2.p-F3_Complex_buf1.p)./F3_Complex_buf2.p);
	% p_err_Gauss = abs((F3_Gauss_buf2.p-F3_Gauss_buf1.p)./F3_Gauss_buf2.p);
	p_err_Complex = abs((F3_Complex_buf2.p-F3_Complex_buf1.p));
	p_err_Gauss = abs((F3_Gauss_buf2.p-F3_Gauss_buf1.p));
	F3.p(p_err_Gauss<p_err_Complex) = F3_Gauss_buf2.p(p_err_Gauss<p_err_Complex);

	if strcmp(ip.Equation, 'Kuznetsov')
		r_err_Complex = abs((F3_Complex_buf2.r-F3_Complex_buf1.r));
		r_err_Gauss = abs((F3_Gauss_buf2.r-F3_Gauss_buf1.r));
		F3.r(r_err_Gauss<r_err_Complex) = F3_Gauss_buf2.r(r_err_Gauss<r_err_Complex);

		theta_err_Complex = abs((F3_Complex_buf2.theta-F3_Complex_buf1.theta));
		theta_err_Gauss = abs((F3_Gauss_buf2.theta-F3_Gauss_buf1.theta));
		% theta_err_Complex = abs((F3_Complex_buf2.theta-F3_Complex_buf1.theta)./F3_Complex_buf2.theta);
		% theta_err_Gauss = abs((F3_Gauss_buf2.theta-F3_Gauss_buf1.theta)./F3_Gauss_buf2.theta);
		F3.theta(theta_err_Gauss<theta_err_Complex) = F3_Gauss_buf2.theta(theta_err_Gauss<theta_err_Complex);
	end
end
